// Daftar chargecode -> kategori partner (dari pembimbing). Kode dipakai sebagai value dropdown,
// kategori dipakai untuk resolve "Related Partner" secara otomatis (terkunci, tidak bisa manual)
// di form Payment Request, dan sebagai opsi filter Chargecode di halaman-halaman payment list.
export const CHARGECODES: [code: string, category: string][] = [
  ['DG-BD-2025', 'Digital'],
  ['DG-BD-AGT-2025', 'Digital'],
  ['DG-BD-CYB-2026', 'Digital'],
  ['DG-CIS-DBC-2026', 'Digital'],
  ['DG-GOG-AI-2025', 'Digital'],
  ['DG-MIC-AIPL-2025', 'Digital'],
  ['DG-OP-2026', 'Digital'],
  ['DG-WB-NDC-2026', 'Digital'],
  ['DG-WHO-CRR-2026', 'Digital'],
  ['ED-BD-2025', 'Education'],
  ['ED-DIK-CNO-2026', 'Education'],
  ['ED-OP-2026', 'Education'],
  ['ED-PLA-YEE-2026', 'Education'],
  ['HH-BD-2025', 'Health'],
  ['HH-BEJ-REGS2-2025', 'Health'],
  ['HH-IPM-INOV-2025', 'Health'],
  ['HH-OP-2026', 'Health'],
  ['HH-UNI-KADR2-2026', 'Health'],
  ['OP-COM-2025', 'Operation'],
  ['OP-FIN-2025', 'Operation'],
  ['OP-GAF-2025', 'Operation'],
  ['OP-HRS-2025', 'Operation'],
  ['OP-IP-AM-2026', 'Operation - Internal Research'],
  ['OP-IP-AR-2025', 'Operation'],
  ['OP-FIN-DIV-2026', 'Operation (dividend)'],
  ['ST-BD-2025', 'Strategy and Transformation'],
  ['ST-BD-CPTL-2026', 'Strategy and Transformation'],
  ['ST-BD-SBY-2026', 'Strategy and Transformation'],
  ['ST-BEJ-AISB-2025', 'Strategy and Transformation'],
  ['ST-BEJ-DHTS2-2025', 'Strategy and Transformation'],
  ['ST-BEJ-SROI-2025', 'Strategy and Transformation'],
  ['ST-OP-2026', 'Strategy and Transformation'],
  ['YM-OTH-INC-2026', 'All AMANA'],
  ['ST-WHO-SSL-2026', 'Strategy and Transformation'],
  ['ST-CIF-GDC-2026', 'Strategy and Transformation'],
  ['ST-FRD-SJD-2026', 'Strategy and Transformation'],
  ['ST-BEJ-HBD-2026', 'Strategy and Transformation'],
  ['ST-MPN-DBRB-2026', 'Strategy and Transformation'],
  ['ST-FSVC-EIT-2026', 'Strategy and Transformation'],
  ['DG-BD-DPI-2026', 'Digital'],
  ['ED-ATR-FLT-2026', 'Education'],
  ['HH-BKPK-ASEAN', 'Health'],
  ['ST-FSVC-ROM-2026', 'Strategy and Transformation'],
  ['ST-GSMA-DMRV-2026', 'Strategy and Transformation'],
];

// Kategori -> department key untuk matching partner. "Operation*"/"All AMANA" semua ke ops (Kevin Tan).
export const CATEGORY_DEPARTMENT: Record<string, string> = {
  Digital: 'digital',
  Education: 'education',
  Health: 'health',
  Operation: 'ops',
  'Operation - Internal Research': 'ops',
  'Operation (dividend)': 'ops',
  'Strategy and Transformation': 'strategy',
  'All AMANA': 'ops',
};

export const chargecodeCategory = new Map(CHARGECODES);
export const CHARGECODE_OPTIONS = Array.from(chargecodeCategory.keys()).sort((a, b) => a.localeCompare(b));
